name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  notes:
    runs-on: vvakame/review:4.0
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: cd notes/src review-pdfmaker config.yml
  build:
    runs-on: rust:1.43.1
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build
